/*
 * This version of the project contains my approach for the Search Engine 
 * project. Anything that is useful will be integrated into the main project.
 * This is not to be used as the main project submission. -Kelvin
 */
package GomezGUI;
import GomezClasses.MyDialogs;
import GomezClasses.FileManager;
import java.io.IOException;
import javax.swing.JOptionPane;
/**
 *
 * @author Kelvin
 */
public class MainInterface extends javax.swing.JFrame {
    /**
     * Creates new form MainInterface
     */
    public MainInterface() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_Maintenance = new javax.swing.JButton();
        label_Heading = new javax.swing.JLabel();
        label_SearchHeading = new javax.swing.JLabel();
        textField_SearchBar = new javax.swing.JTextField();
        button_Search = new javax.swing.JButton();
        button_About = new javax.swing.JButton();
        radioBtn_All = new javax.swing.JRadioButton();
        radioBtn_OrSearch = new javax.swing.JRadioButton();
        radioBtn_PhraseSearch = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea_Results = new javax.swing.JTextArea();
        button_Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frameMainInterface"); // NOI18N

        button_Maintenance.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        button_Maintenance.setText("Maintenance");
        button_Maintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_MaintenanceActionPerformed(evt);
            }
        });

        label_Heading.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        label_Heading.setText("SEARCH ENGINE");

        label_SearchHeading.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        label_SearchHeading.setText("Search:");

        textField_SearchBar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        button_Search.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        button_Search.setText("Search");
        button_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SearchActionPerformed(evt);
            }
        });

        button_About.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        button_About.setText("About");
        button_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_AboutActionPerformed(evt);
            }
        });

        radioBtn_All.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        radioBtn_All.setText("All");
        radioBtn_All.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtn_AllActionPerformed(evt);
            }
        });

        radioBtn_OrSearch.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        radioBtn_OrSearch.setSelected(true);
        radioBtn_OrSearch.setText("Or Search");
        radioBtn_OrSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtn_OrSearchActionPerformed(evt);
            }
        });

        radioBtn_PhraseSearch.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        radioBtn_PhraseSearch.setText("Phrase");
        radioBtn_PhraseSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtn_PhraseSearchActionPerformed(evt);
            }
        });

        textArea_Results.setColumns(20);
        textArea_Results.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        textArea_Results.setRows(5);
        jScrollPane1.setViewportView(textArea_Results);

        button_Exit.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        button_Exit.setText("Exit");
        button_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_Heading)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_SearchHeading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioBtn_All)
                                .addGap(18, 18, 18)
                                .addComponent(radioBtn_OrSearch)
                                .addGap(18, 18, 18)
                                .addComponent(radioBtn_PhraseSearch)
                                .addGap(22, 22, 22)
                                .addComponent(button_Maintenance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_About)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_Exit))
                            .addComponent(textField_SearchBar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_Search)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {button_About, button_Exit, button_Maintenance});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_SearchHeading)
                    .addComponent(textField_SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_Search))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_Maintenance)
                    .addComponent(button_About)
                    .addComponent(radioBtn_All)
                    .addComponent(radioBtn_OrSearch)
                    .addComponent(radioBtn_PhraseSearch)
                    .addComponent(button_Exit))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {button_Search, label_SearchHeading, textField_SearchBar});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {button_About, button_Exit, button_Maintenance});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Disables the other radio buttons when this button is clicked. -Kelvin
     * @param evt 
     */
    private void radioBtn_OrSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtn_OrSearchActionPerformed
        radioBtn_OrSearch.setSelected(true);
        radioBtn_All.setSelected(false);
        radioBtn_PhraseSearch.setSelected(false);
    }//GEN-LAST:event_radioBtn_OrSearchActionPerformed
    /**
     * Displays the About dialog when clicked. -Kelvin
     * @param evt 
     */
    private void button_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_AboutActionPerformed
        new MyDialogs().showAbout();
    }//GEN-LAST:event_button_AboutActionPerformed
    /**
     * Disables the other radio buttons when this button is clicked.
     * @param evt 
     */
    private void radioBtn_AllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtn_AllActionPerformed
        radioBtn_All.setSelected(true);
        radioBtn_OrSearch.setSelected(false);
        radioBtn_PhraseSearch.setSelected(false);
    }//GEN-LAST:event_radioBtn_AllActionPerformed
    /**
     * Disables the other radio buttons when this button is clicked.
     * @param evt 
     */
    private void radioBtn_PhraseSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtn_PhraseSearchActionPerformed
        radioBtn_PhraseSearch.setSelected(true);
        radioBtn_All.setSelected(false);
        radioBtn_OrSearch.setSelected(false);
    }//GEN-LAST:event_radioBtn_PhraseSearchActionPerformed
    /**
     * Displays the Index Maintenance window.
     * @param evt 
     */
    private void button_MaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_MaintenanceActionPerformed
        new Maintenance().setVisible(true);
        
        FileManager manage = new FileManager();    
        try {
            manage.readFile();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,"File not found.","Error",
            JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_button_MaintenanceActionPerformed
    /**
     * Exits the application when clicked.
     * @param evt 
     */
    private void button_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_button_ExitActionPerformed
    /**
     * Searches the file index.
     * @param evt 
     */
    private void button_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SearchActionPerformed
        new MyDialogs().showTempOut(); //*****Temporary Placeholder*****
    }//GEN-LAST:event_button_SearchActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /**
         * Brings up the Main Interface when
         * the program runs. -Kelvin
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_About;
    private javax.swing.JButton button_Exit;
    private javax.swing.JButton button_Maintenance;
    private javax.swing.JButton button_Search;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_Heading;
    private javax.swing.JLabel label_SearchHeading;
    public javax.swing.JRadioButton radioBtn_All;
    public javax.swing.JRadioButton radioBtn_OrSearch;
    public javax.swing.JRadioButton radioBtn_PhraseSearch;
    private javax.swing.JTextArea textArea_Results;
    private javax.swing.JTextField textField_SearchBar;
    // End of variables declaration//GEN-END:variables
}