package com.bkj.search.bradGUI;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 * @see Runnable
 * @since 0.1
 */
public class NotImplementedDialog extends JDialog
        implements Runnable {

    private JPanel contentPanel;
    private JButton buttonOK;
    private JButton buttonCancel;
    private JLabel dialogMessage;
    private JPanel buttonsPanel;
    private JPanel messagePanel;

    /**
     * creates a 'blank' NotImplementedDialog
     *
     * @see NotImplementedDialog::NotImplementedDialog(String,String)
     */
    public NotImplementedDialog() {
        new NotImplementedDialog("UNKNOWN", "NO MESSAGE");
    }

    /**
     * Creates a NotImplemented Dialog
     *
     * @param title   Title of the dialog window to create
     * @param message Message to be displayed in dialog window
     */
    public NotImplementedDialog(String title, String message) {
        setContentPane(contentPanel);
        setModal(true);
        getRootPane().setDefaultButton(buttonOK);

        buttonOK.addActionListener(e -> onOK());

        buttonCancel.addActionListener(e -> onCancel());

        // call onCancel() when cross is clicked
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                onCancel();
            }
        });

        // call onCancel() on ESCAPE
        contentPanel.registerKeyboardAction(e -> onCancel(),
                KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
                JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);

        setTitle(title);
        dialogMessage.setText(message);


    }

    /**
     * Handles on exit tasks when 'Ok' is pressed
     */
    private void onOK() {
        dispose();
    }

    /**
     * Handles on exit tasks when 'Cancel' is pressed or exiting
     */
    private void onCancel() {
        dispose();
    }

    /**
     * calls JDialog::pack and sets the dialog visible
     *
     * @see Runnable
     */
    @Override
    public void run() {
        pack();
        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new BorderLayout(0, 0));
        messagePanel = new JPanel();
        messagePanel.setLayout(new BorderLayout(0, 0));
        contentPanel.add(messagePanel, BorderLayout.CENTER);
        dialogMessage = new JLabel();
        dialogMessage.setText("No Message");
        messagePanel.add(dialogMessage, BorderLayout.CENTER);
        buttonsPanel = new JPanel();
        buttonsPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        contentPanel.add(buttonsPanel, BorderLayout.SOUTH);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        buttonsPanel.add(panel1);
        buttonOK = new JButton();
        buttonOK.setText("OK");
        panel1.add(buttonOK, BorderLayout.WEST);
        buttonCancel = new JButton();
        buttonCancel.setText("Cancel");
        panel1.add(buttonCancel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }
}
