package com.bkj.search.gui;

import javax.swing.*;
import java.awt.*;

/**
 * @since 0.1
 * @see java.lang.Runnable
 */
public class AdministrationWindow implements Runnable {
    private JPanel topPanel;
    private JPanel optionsPanel;
    private JPanel indexedFilesPanel;
    private JTable indexedFilesTable;
    private JButton removeIndexButton;
    private JButton updateIndexButton;
    private JButton addIndexButton;
    private JButton closeFormButton;

    private JFrame mainFrame;

    /**
     * Creates a default Administration Window to manage index files
     */
    public AdministrationWindow() {
        $$$setupUI$$$();
        closeFormButton.addActionListener(actionEvent -> mainFrame.dispose());

        addIndexButton.addActionListener(actionEvent -> {
            // TODO: event handler for adding a index directly
        });
        removeIndexButton.addActionListener(actionEvent -> {
            // TODO: event handler for removing a index directly
        });
        updateIndexButton.addActionListener(actionEvent -> {
            // TODO: event handler to force a update of a index from the backing file
        });

        mainFrame.setContentPane($$$getRootComponent$$$());
        mainFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        mainFrame.setPreferredSize(new Dimension(400, 400));
    }

    /**
     * calls JDialog::pack and sets the dialog visible
     * @see java.lang.Runnable
     */
    @Override
    public void run() {
        mainFrame.pack();
        mainFrame.setVisible(true);
    }

    /**
     * For UI components marked 'Custom Create'
     * <p>
     *     Intellij generates the $$$setupUI$$$() method and calls createUIComponents()
     *     this allows greater control over how objects are made instead of the default
     *     parameter-less constructor
     * </p>
     */
    private void createUIComponents() {
        // TODO: place custom component creation code here
        mainFrame = new JFrame("Index Administration");

        String[] columnNames = {"File",
                "Status"};

        Object[][] data = {
                {"testdata1.txt", "Indexed"},
                {"testdata4.txt", "Indexed"},
                {"testdata5.txt", "Out of Date"},
                {"testdata11.txt", "Indexed"},
                {"testdata15.txt", "Indexed"}
        };

        indexedFilesTable = new JTable(data, columnNames);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        topPanel = new JPanel();
        topPanel.setLayout(new BorderLayout(0, 0));
        optionsPanel = new JPanel();
        optionsPanel.setLayout(new GridBagLayout());
        topPanel.add(optionsPanel, BorderLayout.NORTH);
        removeIndexButton = new JButton();
        removeIndexButton.setText("Remove Index");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        optionsPanel.add(removeIndexButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        optionsPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        optionsPanel.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        optionsPanel.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        optionsPanel.add(spacer4, gbc);
        updateIndexButton = new JButton();
        updateIndexButton.setText("Update Index");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        optionsPanel.add(updateIndexButton, gbc);
        addIndexButton = new JButton();
        addIndexButton.setText("Add Index");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        optionsPanel.add(addIndexButton, gbc);
        indexedFilesPanel = new JPanel();
        indexedFilesPanel.setLayout(new BorderLayout(0, 0));
        topPanel.add(indexedFilesPanel, BorderLayout.CENTER);
        indexedFilesPanel.add(indexedFilesTable, BorderLayout.CENTER);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        topPanel.add(panel1, BorderLayout.SOUTH);
        closeFormButton = new JButton();
        closeFormButton.setText("Close");
        panel1.add(closeFormButton, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return topPanel;
    }
}
