package com.bkj.search.gui;

import com.bkj.search.utils.FileInvertedIndex;
import com.bkj.search.utils.InvertedIndexEntry;
import com.bkj.search.utils.Pair;
import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.*;

/**
 * @see Runnable
 * @since 0.1
 */
public class AdministrationWindow implements Runnable {
    private JPanel topPanel;
    private JPanel optionsPanel;
    private JPanel indexedFilesPanel;
    private JTable indexedFilesTable;
    private JButton removeIndexButton;
    private JButton updateIndexButton;
    private JButton addIndexButton;
    private JButton closeFormButton;

    private JFrame mainFrame;
    private final MainWindow mw;
    private final TreeMap<String, Date> openFiles;
    private TreeMap<String, Boolean> indexedFilesMap;
    private DefaultTableModel indexedFilesTableModel;

    /**
     * Creates a default Administration Window to manage index files
     */
    public AdministrationWindow(MainWindow mw) {
        this.mw = mw;
        openFiles = mw.getOpenFiles();
        indexedFilesMap = new TreeMap<>();
        // we create the default state here, which is everything is *not* indexed
        for (String file : openFiles.keySet()) {
            indexedFilesMap.put(file, false);
        }
        $$$setupUI$$$();


        closeFormButton.addActionListener(actionEvent -> mainFrame.dispose());

        addIndexButton.addActionListener(actionEvent -> {
            // TODO: event handler for adding a index directly
        });
        removeIndexButton.addActionListener(actionEvent -> {
            // TODO: event handler for removing a index directly
        });
        updateIndexButton.addActionListener(actionEvent -> {
            // TODO: event handler to force a update of a index from the backing file
        });

        mainFrame.setContentPane($$$getRootComponent$$$());
        mainFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        mainFrame.setPreferredSize(new Dimension(850, 250));
    }

    /**
     * calls JDialog::pack and sets the dialog visible
     *
     * @see Runnable
     */
    @Override
    public void run() {
        System.out.printf("Opening %d files for indexing\n", openFiles.size());
        for (String s : openFiles.keySet()) {
            mw.addIndexedFile(new FileInvertedIndex(s));
        }

        System.out.printf("Rebuilding %d indexes\n", mw.getIndexedFiles().size());
        for (FileInvertedIndex fii : mw.getIndexedFiles()) {
            System.out.printf("\t> Rebuilding %s...\n", fii.getFileString());
            fii.rebuildIndex();
        }
        mainFrame.pack();
        mainFrame.setVisible(true);
    }

    /**
     * For UI components marked 'Custom Create'
     * <p>
     * Intellij generates the $$$setupUI$$$() method and calls createUIComponents()
     * this allows greater control over how objects are made instead of the default
     * parameter-less constructor
     * </p>
     */
    private void createUIComponents() {
        // TODO: place custom component creation code here
        mainFrame = new JFrame("Index Administration");

        indexedFilesTableModel = makeTableModel(indexedFilesMap);
        indexedFilesTable = new JTable(indexedFilesTableModel);
    }

    private DefaultTableModel makeTableModel(Map<String, Boolean> map) {
        DefaultTableModel model = new DefaultTableModel(
                new Object[]{"File", "Indexed?"}, 0
        );
        for (Map.Entry<String, Boolean> entry : map.entrySet()) {
            model.addRow(new Object[]{entry.getKey(), entry.getValue()});
        }
        return model;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        topPanel = new JPanel();
        topPanel.setLayout(new BorderLayout(0, 0));
        optionsPanel = new JPanel();
        optionsPanel.setLayout(new GridBagLayout());
        topPanel.add(optionsPanel, BorderLayout.NORTH);
        removeIndexButton = new JButton();
        removeIndexButton.setText("Remove Index");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        optionsPanel.add(removeIndexButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        optionsPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        optionsPanel.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        optionsPanel.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        optionsPanel.add(spacer4, gbc);
        updateIndexButton = new JButton();
        updateIndexButton.setText("Update Index");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        optionsPanel.add(updateIndexButton, gbc);
        addIndexButton = new JButton();
        addIndexButton.setText("Add Index");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        optionsPanel.add(addIndexButton, gbc);
        indexedFilesPanel = new JPanel();
        indexedFilesPanel.setLayout(new BorderLayout(0, 0));
        topPanel.add(indexedFilesPanel, BorderLayout.CENTER);
        closeFormButton = new JButton();
        closeFormButton.setText("Close");
        indexedFilesPanel.add(closeFormButton, BorderLayout.SOUTH);
        final JScrollPane scrollPane1 = new JScrollPane();
        indexedFilesPanel.add(scrollPane1, BorderLayout.CENTER);
        scrollPane1.setViewportView(indexedFilesTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return topPanel;
    }
}
