package com.bkj.search.gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

/**
 * Created by bclaus on 2/9/17.
 */
public class MainWindow {
    private JPanel mainPane;
    private JButton doSearchButton;
    private JTextField searchTextField;
    private JTabbedPane tabbedPane1;
    private JTable resultsTable;
    private JProgressBar progressBar1;
    private JButton chooseFilesButton;
    private JList<String> searchFilesList;
    private JButton removeSelectedFileButton;
    private JButton selectDBButton;
    private JButton aboutButton;
    private JTextField databaseFileTextField;
    private JCheckBox saveDatabaseCheckbox;
    private JButton adminPageButton;
    private JComboBox comboBox1;
    private JCheckBox checkBox3;

    private DefaultListModel<String> listModel;
    private JFileChooser searchFilesChooser;
    private int fcRetval;

    public MainWindow() {
        $$$setupUI$$$();

        searchFilesChooser = new JFileChooser();

        doSearchButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                NotImplementedDialog d = new NotImplementedDialog("Not Implemented", "Searching does not work yet");
            }
        });
        
        selectDBButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                NotImplementedDialog d = new NotImplementedDialog("Not Implemented", "Database path does not work yet");
            }
        });
        
        aboutButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                AboutWindow win = new AboutWindow();
                win.getAccessibleContext();
                win.setVisible(true);
            }
        });

        chooseFilesButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                int fcRetVal = searchFilesChooser.showOpenDialog(mainPane);

                if (fcRetval == JFileChooser.APPROVE_OPTION) {
                    File file = searchFilesChooser.getSelectedFile();
                    //This is where a real application would open the file.
                    listModel.addElement(file.toPath().toString());
                } else {
                    // Canceled
                }
            }
        });


        removeSelectedFileButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                try {
                    listModel.remove(searchFilesList.getSelectedIndex());
                } catch (ArrayIndexOutOfBoundsException aie) {
                    NotImplementedDialog d = new NotImplementedDialog("Whoops!", "Select a file to remove");
                }
            }
        });
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        // Note that this is not the place for NEW components
        // It is only to setup components that have been marked custom

        listModel = new DefaultListModel<String>();
        searchFilesList = new JList<>(listModel);


        // This is just test data so the table shows up
        // everything here is subject to change
        String[] columnNames = {"Name",
                "Super Power",
                "Can Fly?"};

        Object[][] data = {
                {"Batman", "Money", Boolean.FALSE},
                {"Superman", "Everything", Boolean.TRUE},
                {"Flash", "Really fast", Boolean.FALSE},
                {"Goku", "Can't Die :^)", Boolean.TRUE},
                {"The Hulk", "Turns Green & Angry", Boolean.FALSE}
        };

        resultsTable = new JTable(data, columnNames);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPane = new JPanel();
        mainPane.setLayout(new BorderLayout(0, 0));
        final JPanel topPanel = new JPanel();
        topPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        mainPane.add(topPanel, BorderLayout.NORTH);
        topPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        final JLabel searchLabel = new JLabel();
        searchLabel.setText("Search ");
        topPanel.add(searchLabel);
        searchTextField = new JTextField();
        searchTextField.setColumns(20);
        topPanel.add(searchTextField);
        doSearchButton = new JButton();
        doSearchButton.setText("Go");
        topPanel.add(doSearchButton);
        comboBox1 = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("AND");
        defaultComboBoxModel1.addElement("OR");
        defaultComboBoxModel1.addElement("PHRASE");
        comboBox1.setModel(defaultComboBoxModel1);
        topPanel.add(comboBox1);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        mainPane.add(panel2, BorderLayout.CENTER);
        tabbedPane1 = new JTabbedPane();
        panel2.add(tabbedPane1, BorderLayout.CENTER);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        tabbedPane1.addTab("Search Results", panel3);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel3.add(scrollPane1, BorderLayout.CENTER);
        resultsTable.putClientProperty("Table.isFileList", Boolean.FALSE);
        scrollPane1.setViewportView(resultsTable);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        tabbedPane1.addTab("Files", panel4);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new BorderLayout(0, 0));
        panel4.add(panel5, BorderLayout.NORTH);
        chooseFilesButton = new JButton();
        chooseFilesButton.setText("Choose Files...");
        panel5.add(chooseFilesButton, BorderLayout.CENTER);
        panel4.add(searchFilesList, BorderLayout.CENTER);
        removeSelectedFileButton = new JButton();
        removeSelectedFileButton.setHorizontalAlignment(0);
        removeSelectedFileButton.setText("Remove Selected File");
        panel4.add(removeSelectedFileButton, BorderLayout.SOUTH);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridBagLayout());
        tabbedPane1.addTab("Settings", panel6);
        final JLabel label2 = new JLabel();
        label2.setText("Database path");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel6.add(label2, gbc);
        selectDBButton = new JButton();
        selectDBButton.setText("Select DB");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel6.add(selectDBButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel6.add(spacer1, gbc);
        aboutButton = new JButton();
        aboutButton.setText("About...");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel6.add(aboutButton, gbc);
        databaseFileTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel6.add(databaseFileTextField, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel6.add(spacer2, gbc);
        saveDatabaseCheckbox = new JCheckBox();
        saveDatabaseCheckbox.setText("Save database to disk");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel6.add(saveDatabaseCheckbox, gbc);
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new BorderLayout(0, 0));
        mainPane.add(panel7, BorderLayout.SOUTH);
        final JToolBar toolBar1 = new JToolBar();
        panel7.add(toolBar1, BorderLayout.CENTER);
        adminPageButton = new JButton();
        adminPageButton.setText("Admin");
        toolBar1.add(adminPageButton);
        progressBar1 = new JProgressBar();
        toolBar1.add(progressBar1);
        searchLabel.setLabelFor(searchTextField);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPane;
    }
}
