/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bkj.search.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
/**
 *
 * @author Kelvin
 */
public class MaintenanceWindow extends javax.swing.JFrame {

    /**
     * Creates new form MaintenanceWindow
     */
    // Creates a file chooser
    final JFileChooser fc = new JFileChooser();
    JTextArea log;
    
    public MaintenanceWindow() {
        initComponents();
        
         // Adds action listeners for buttons
         Return.addActionListener(new ActionListener () {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                NotImplementedDialog d = new NotImplementedDialog("Not Implemented", "Return button does not work yet");
            }
        });
        // Adds action listeners for buttons
        Update.addActionListener(new ActionListener () {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                NotImplementedDialog d = new NotImplementedDialog("Not Implemented", "Update button does not work yet");
            }
        });
        // Adds action listeners for buttons
        Remove.addActionListener(new ActionListener () {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                NotImplementedDialog d = new NotImplementedDialog("Not Implemented", "Remove button does not work yet");
            }
        });
        // Brings up a file chooser.-Kelvin
        AddFile.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                if (actionEvent.getSource() == AddFile) {
                    int returnVal;
                    returnVal = fc.showOpenDialog(MaintenanceWindow.this);

                    if (returnVal == JFileChooser.APPROVE_OPTION) {
                    File file = fc.getSelectedFile();
                    //This is where a real application would open the file.
                    log.append("Opening: " + file.getName() + "." + "\n");
                    } else {
                        log.append("Open command cancelled by user." + "\n");
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        // Initializes components
        panelMaintenanceWindow = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        myPane = new javax.swing.JScrollPane();
        MaintenanceTable = new javax.swing.JTable();
        AddFile = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Return = new javax.swing.JButton();

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHeader.setText("Index Maintenace");

        MaintenanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "File", "Status"
            }
        ));
        myPane.setViewportView(MaintenanceTable);

        AddFile.setText("Add File");
        AddFile.setToolTipText("");

        Remove.setText("Remove");

        Update.setText("Update");

        Return.setText("Return...");

        javax.swing.GroupLayout panelMaintenanceWindowLayout = new javax.swing.GroupLayout(panelMaintenanceWindow);
        panelMaintenanceWindow.setLayout(panelMaintenanceWindowLayout);
        panelMaintenanceWindowLayout.setHorizontalGroup(
            panelMaintenanceWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMaintenanceWindowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHeader)
                .addGap(104, 104, 104))
            .addComponent(myPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(panelMaintenanceWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMaintenanceWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Return, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelMaintenanceWindowLayout.createSequentialGroup()
                        .addComponent(AddFile)
                        .addGap(95, 95, 95)
                        .addComponent(Remove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(Update)))
                .addContainerGap())
        );
        panelMaintenanceWindowLayout.setVerticalGroup(
            panelMaintenanceWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMaintenanceWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(panelMaintenanceWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddFile)
                    .addComponent(Remove)
                    .addComponent(Update))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myPane, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(Return))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMaintenanceWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMaintenanceWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_ReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaintenanceWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaintenanceWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaintenanceWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaintenanceWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Displays Window
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaintenanceWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFile;
    private javax.swing.JTable MaintenanceTable;
    private javax.swing.JButton Remove;
    private javax.swing.JButton Return;
    private javax.swing.JButton Update;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JScrollPane myPane;
    private javax.swing.JPanel panelMaintenanceWindow;
    // End of variables declaration//GEN-END:variables
}
